version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.0

jobs:
  install-deps:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  build:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build application
          command: yarn build

workflows:
  version: 2
  build-and-test:
    jobs:
      - install-deps
      - build:
          requires:
            - install-deps
